Plugin.define do
	name "Plugin-Tutorial-1"
	authors [
		"Your preferred name email@address", 
	]
	version "0.1"
	description "Generic CMS is an open-source Management System developed in PHP."
	website "http://example.com/"

	matches [
	{ :text => "This page was generated by <b>Generic CMS</b>" },

	{ :regexp => /This page was generated by <a href="http:\/\/www.genericcms.com\/en\/products\/generic-cms\/">Generic CMS<\/a>/ },
	
	{ :name => "Meta generator",  :version => /<meta name="generator" content="Generic CMS version ([a-z0-9])+/ },
	] 

end